const API_URL = 'http://91.185.86.61:8080';
const VIDEO_UPLOAD_URL = `${API_URL}/save`;
const VIDEO_PARSE_URL = `${API_URL}/tiflocommented`;
const DOWNLOAD_VIDEO_PARSE_URL = `${API_URL}/getprocessed`;
const EVALUATION_POST_URL = `${API_URL}/feedback`;

export { API_URL, VIDEO_UPLOAD_URL, VIDEO_PARSE_URL, DOWNLOAD_VIDEO_PARSE_URL, EVALUATION_POST_URL };